web: waitress-serve --host=0.0.0.0 --port=$PORT myprofile.wsgi:application
#web: waitress-serve --port=$PORT myprofile.wsgi:application
#web gunicorn myprofile.wsgi.application --log-file -
release: bash build.sh