services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python waitress_server.py"
    #envVars:
     # - key: PYTHONPATH
       #value: /opt/render/project/src
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myprofile.settings
    
